//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HotelDbConnection : DbContext
    {
        public HotelDbConnection()
            : base("name=HotelDbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiViet> BaiViets { get; set; }
        public virtual DbSet<DatPhong> DatPhongs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiDichVu> LoaiDichVus { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuDatPhongKhachSan> PhieuDatPhongKhachSans { get; set; }
        public virtual DbSet<PhieuDichVu> PhieuDichVus { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<GET_LIST_ROOM_Result> GET_LIST_ROOM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LIST_ROOM_Result>("GET_LIST_ROOM");
        }
    
        public virtual ObjectResult<GET_SERVICE_ALL_Result> GET_SERVICE_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SERVICE_ALL_Result>("GET_SERVICE_ALL");
        }
    
        public virtual int ADD_LIST_SERVICE(string tenDichVu, string donViTinh, Nullable<int> gia, string imgDichVu)
        {
            var tenDichVuParameter = tenDichVu != null ?
                new ObjectParameter("TenDichVu", tenDichVu) :
                new ObjectParameter("TenDichVu", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(int));
    
            var imgDichVuParameter = imgDichVu != null ?
                new ObjectParameter("imgDichVu", imgDichVu) :
                new ObjectParameter("imgDichVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_LIST_SERVICE", tenDichVuParameter, donViTinhParameter, giaParameter, imgDichVuParameter);
        }
    
        public virtual int DELETE_ITEM_SERVICE(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_ITEM_SERVICE", iDParameter);
        }
    
        public virtual ObjectResult<GET_POSTS_Result> GET_POSTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_POSTS_Result>("GET_POSTS");
        }
    
        public virtual int UPDATE_ITEM_SERVICE(Nullable<int> iD, string tenDichVu, string donViTinh, Nullable<int> gia, string imgDichVu)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tenDichVuParameter = tenDichVu != null ?
                new ObjectParameter("TenDichVu", tenDichVu) :
                new ObjectParameter("TenDichVu", typeof(string));
    
            var donViTinhParameter = donViTinh != null ?
                new ObjectParameter("DonViTinh", donViTinh) :
                new ObjectParameter("DonViTinh", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(int));
    
            var imgDichVuParameter = imgDichVu != null ?
                new ObjectParameter("imgDichVu", imgDichVu) :
                new ObjectParameter("imgDichVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_ITEM_SERVICE", iDParameter, tenDichVuParameter, donViTinhParameter, giaParameter, imgDichVuParameter);
        }
    
        public virtual ObjectResult<GET_LIST_POSTS_Result> GET_LIST_POSTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_LIST_POSTS_Result>("GET_LIST_POSTS");
        }
    
        public virtual ObjectResult<GET_SERVICE_ALL1_Result> GET_SERVICE_ALL1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_SERVICE_ALL1_Result>("GET_SERVICE_ALL1");
        }
    
        public virtual int ADD_LIST_ROOM(string tenLoaiPhong, Nullable<int> giaPhong, string imgLoaiPhong)
        {
            var tenLoaiPhongParameter = tenLoaiPhong != null ?
                new ObjectParameter("TenLoaiPhong", tenLoaiPhong) :
                new ObjectParameter("TenLoaiPhong", typeof(string));
    
            var giaPhongParameter = giaPhong.HasValue ?
                new ObjectParameter("GiaPhong", giaPhong) :
                new ObjectParameter("GiaPhong", typeof(int));
    
            var imgLoaiPhongParameter = imgLoaiPhong != null ?
                new ObjectParameter("imgLoaiPhong", imgLoaiPhong) :
                new ObjectParameter("imgLoaiPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_LIST_ROOM", tenLoaiPhongParameter, giaPhongParameter, imgLoaiPhongParameter);
        }
    
        public virtual int DELETE_ITEM_ROOM(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_ITEM_ROOM", iDParameter);
        }
    
        public virtual int UPDATE_ITEM_ROOM(Nullable<int> iD, string tenLoaiPhong, Nullable<int> giaPhong, string imgLoaiPhong)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var tenLoaiPhongParameter = tenLoaiPhong != null ?
                new ObjectParameter("TenLoaiPhong", tenLoaiPhong) :
                new ObjectParameter("TenLoaiPhong", typeof(string));
    
            var giaPhongParameter = giaPhong.HasValue ?
                new ObjectParameter("GiaPhong", giaPhong) :
                new ObjectParameter("GiaPhong", typeof(int));
    
            var imgLoaiPhongParameter = imgLoaiPhong != null ?
                new ObjectParameter("imgLoaiPhong", imgLoaiPhong) :
                new ObjectParameter("imgLoaiPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_ITEM_ROOM", iDParameter, tenLoaiPhongParameter, giaPhongParameter, imgLoaiPhongParameter);
        }
    }
}
