//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDichVu
    {
        public int ID { get; set; }
        public int idDatPhong { get; set; }
        public System.DateTime NgayDat { get; set; }
        public int idDichVu { get; set; }
        public int SoLuong { get; set; }
        public decimal Gia { get; set; }
        public int TinhTrang { get; set; }
        public int idNv { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
